# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-29 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(max_length=5)),
                ('product_desc', models.TextField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2018, 7, 29, 5, 49, 26, 400053))),
            ],
        ),
    ]
