# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-29 05:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180729_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 29, 5, 52, 8, 685671, tzinfo=utc)),
        ),
    ]
