# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-29 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180729_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 29, 7, 32, 58, 586905, tzinfo=utc)),
        ),
    ]
